Oksana work art
AlexDubin/15-16team-interior-design pull request #9
Opened 2023-02-12 16:15 UTC by OksanaLynnyk

2023-02-12 16:33 UTC, AlexDubin approved these changes

2023-02-12 16:34 UTC, AlexDubin requested changes
Решить конфликт, как на уроке с ментором

2023-02-12 18:44 UTC, AlexDubin approved these changes

2023-02-12 18:47 UTC, AlexDubin requested changes
Решить конфликт

2023-02-12 18:48 UTC, AlexDubin approved these changes

2023-02-12 18:48 UTC, AlexDubin requested changes
Решить конфликт

2023-02-13 17:09 UTC, AlexDubin approved these changes

2023-02-13 17:09 UTC, AlexDubin approved these changes

2023-02-13 17:46 UTC, OleksandKr approved these changes

2023-02-13 22:32 UTC, closed without merging